# Disable the blank line at the start of the prompt
add_newline = true

# ãƒ†ã‚­ã‚¹ãƒˆãŒå…¥åŠ›ã•ã‚Œã‚‹å ´æ‰€ã‚’ç¤ºã™æ–‡å­—ã®è¨­å®š
[character]
# symbol = "$" # æ–‡å­—ã‚’å¤‰æ›´(ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¯ > )
error_symbol = "[â¯](bold red)"
success_symbol = "[â¯](bold green)"


[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"


# æ”¹è¡Œè‡ªä½“ã®è¨­å®š
[line_break]
disabled = true # éè¡¨ç¤ºã«è¨­å®š

# æ™‚é–“ã®è¨­å®š
[time]
disabled = true # éè¡¨ç¤ºã«è¨­å®šã™ã‚‹ã¨ã€å¿…ãšä¸€è¡Œã«ãªã‚‹

# gitã®ãƒ–ãƒ©ãƒ³ãƒã®è¡¨ç¤º
[git_branch]
symbol = "ğŸŒ± " #ã‚¢ã‚¤ã‚³ãƒ³çµµæ–‡å­—ã‚’å¤‰æ›´

